### PR TITLE
[ASPA-016] Fixing base_url() under different development environments

### PR DESCRIPTION
**Pull request by lucas2005gao**
Currently, there are 4 different possible development environments:
1. Server with the hostname of https://aspa.wdcc.co.nz
2. Windows machine with XAMPP with the root directory located at http://localhost/ASPA-Folder/
3. Windows machine with XAMPP with the root directory located at http://localhost/
4. MacOSX machines with MAMP with the root directory of http://localhost:8080/

**Issue:**
With different development environments above, the base_url() should be different. 
If we leave the base_url() as empty in master branch, then we will need to manually change it every time upon deployment.
If we set base_url() in localhost and server to be
'$config['base_url'] = 'http://' . $_SERVER['HTTP_HOST'] . '/'; '
and 
'$config['base_url'] = 'https://' . $_SERVER['HTTP_HOST'] . '/'; '
respectively, then we face the issue of the base_url() not working under development environment No.2

With respect to frontend Ajax calls, the EnrollmentForm.js file is able to grab the base_url defined in PHP from a hidden div tag with base_url echoed in PHP in the main frontend page.

**Solutions:**
Leaving the base_url to be automatically detected under the localhost environment. Leaving server-side base_url() unchanged. Also changing all the view <link> and tags with reference to assets files to attach the new automatically detected base_url()

**Risk:**
If the base_url() set up does not work under someone's development environment then they may not be able to develop

**Reviewed By:**
Raymond, Martin, Anubhav

### CODE REVIEW

**Comment by Ray-F** [comment]
image
System: Windows 10, Chrome w/ localhost at localhost:80 (using XAMPP)

Base URL does not work

**Comment by Ray-F** [comment]
Mac OS w/ Chrome on MAMP (localhost:8888) seems to work.

**Comment by lucas2005gao** [comment]
The problem should now be fixed.

**Review by Ray-F — APPROVED** [review]
Both working for me now, tested against email validation step and Stripe Payment method (which should contain all instances of base_url being used)

**Review by Will-ZYS — APPROVED** [review]

**Pull request merged**
